### ISSUE TITLE
usb.h contains references to the PowerBoard.

### ISSUE THREAD

**Issue by trickeydan** [j5api/sr-servo-v4-fw#1]

**Comment by kierdavis** [comment]
It looks like none of these constants are used in the [USB protocol implementation](https://github.com/j5api/sr-servo-v4-fw/blob/master/sbusb.c), except for [this one](https://github.com/j5api/sr-servo-v4-fw/blob/master/sbusb.c#L86). This could do with a good cleanup.

**Comment by trickeydan** [comment]
Upstream: https://github.com/srobo/servo-v4-fw/issues/3
